export const SET_POKEMONS = "SET_POKEMONS";
export const SET_POKEMON_DETAIL = "SET_POKEMON_DETAIL";
export const SET_POKEMON_FAVORITE = "SET_POKEMON_FAVORITE";
export const SET_LOADING = "SET_LOADING";
